# Generated by Django 4.1.2 on 2023-01-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontact",
            name="phone_number",
            field=models.CharField(default="000", max_length=16),
        ),
    ]
