# Generated by Django 4.1.2 on 2022-12-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_store_owner_alter_image_image_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="image_url",),
        migrations.RemoveField(model_name="image", name="product",),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(to="stores.image"),
        ),
    ]
