# Generated by Django 4.1.2 on 2023-04-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_contact_phone_store_country_store_international_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='discount_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.discountpolicy'),
        ),
    ]
