# Generated by Django 4.1.2 on 2023-04-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_discountpolicy_store_discount_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Cost Price(In Naira)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Selling Price(In Naira)'),
        ),
    ]
