# Generated by Django 4.1.2 on 2023-04-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_remove_product_price_alter_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
