# Generated by Django 4.1.2 on 2022-12-16 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivedorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="userapp.order"
            ),
        ),
    ]
